<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="dataSourceStorageLocal">
    <data-source name="demo.py" uuid="c25aa43e-2394-4e4b-b358-1c9d32bd3563">
      <database-info product="SQLite" version="3.16.1" jdbc-version="2.1" driver-name="SQLiteJDBC" driver-version="native" />
      <case-sensitivity plain-identifiers="mixed" quoted-identifiers="mixed" />
      <secret-storage>master_key</secret-storage>
      <auth-required>false</auth-required>
    </data-source>
    <data-source name="TypeError: create_table() takes exactly 1 argument (0 given)" uuid="ad5a4e6b-241b-4f3f-ae01-4419e6aa4eaa">
      <database-info product="SQLite" version="3.16.1" jdbc-version="2.1" driver-name="SQLiteJDBC" driver-version="native" />
      <case-sensitivity plain-identifiers="mixed" quoted-identifiers="mixed" />
      <secret-storage>master_key</secret-storage>
      <auth-required>false</auth-required>
      <introspection-schemas>*:main</introspection-schemas>
    </data-source>
    <data-source name="users" uuid="f19a66bb-93e7-42c2-9567-1af14f92a331">
      <database-info product="SQLite" version="3.16.1" jdbc-version="2.1" driver-name="SQLiteJDBC" driver-version="native" />
      <case-sensitivity plain-identifiers="mixed" quoted-identifiers="mixed" />
      <secret-storage>master_key</secret-storage>
      <auth-required>false</auth-required>
      <introspection-schemas>*:main</introspection-schemas>
    </data-source>
    <data-source name="Users.db') Base.metadata.create_all(engine)" uuid="e59161f4-4591-4a1f-959f-49a97411ef50">
      <database-info product="" version="" jdbc-version="" driver-name="" driver-version="" />
      <secret-storage>master_key</secret-storage>
      <auth-required>false</auth-required>
      <first-sync>true</first-sync>
    </data-source>
  </component>
</project>